package:
  name: phenotool
  version: "0.12"

source:
  git_url: &github https://github.com/carsten0202/phenotool
  path: ..

build:
  entry_points:
    - incidence = eastwood.cli:incidence
    - phenotool = phenotool.phenotool:main
    - prevalence = eastwood.cli:prevalence
    - ukbiobank = ukbiobank.ukbiobank:main

requirements:
  build:
    - python >=3.8
    - setuptools >=49.0

  host:
    - python >=3.8
    - click >=7.1
    - numpy >=1.16
    - pandas >=1.2

  run:
    - python >=3.8
    - click >=7.1
    - numpy >=1.16
    - pandas >=1.2

about:
  home: *github
  license: GPLv3
  license_file: LICENSE
  summary: Write summary here

